name: Build Packages

on:
  workflow_dispatch:
    inputs:
      ssh:
            description: '是否开启ssh调试'
            required: true
            default: 'false'
            type: choice
            options:
              - 'true'
              - 'false'
jobs:
  build:
    name: ssh
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: SSH connection to Actions
        uses: P3TERX/ssh2actions@main
        if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
        env:
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
